### ISSUE TITLE
Maybe google did changed it's workflow?

### ISSUE THREAD

**Issue by ArshCypherZ** [Black-Bulls-Bots/google-reverse-search#1]
https://spaceb.in/bSoLUOyB : Traceback of what i got while using your package.

**Comment by jk6521** [comment]
@ArshCypherZ Will check

**Comment by jk6521** [comment]
Yeah I have checked the issue, will try to fix this ASAP.
thanks for letting me know.

**Comment by ArshCypherZ** [comment]
let me know if its done, its urgent for me
